Parameters:
  Tag:
    Type: String
    Default: latest

  Name:
    Type: String

  ContainerName:
    Type: String

  ContainerPort:
    Type: Number
    Default: 3000

  Port:
    Type: Number
    Default: 3000

  DesiredCount:
    Type: Number
    Default: 0

  LoadBalancerName:
    Type: String

  Cluster:
    Type: String

  Repository:
    Type: String

  RdsDbName:
    Type: String

  RdsHostname:
    Type: String

  RdsUsername:
    Type: String

  RdsPassword:
    Type: String

  AwslogsGroup:
    Type: String

  AwslogsStreamPrefix:
    Type: String

  DynamoDbEndpoint:
    Type: String
    Default: dynamodb.us-east-1.amazonaws.com

  SnsEndpoint:
    Type: String
    Default: sns.us-east-1.amazonaws.com

  AwsRegion:
    Type: String

  AwsAccessKey:
    Type: String

  AwsSecretKey:
    Type: String

  Environment:
    Type: String

  GitHubToken:
    Type: String

  EcsRoleArn:
    Type: String

  Memory:
    Type: Number
    Default: 512

  Cpu:
    Type: Number
    Default: 128

Resources:

  Service:
    Type: AWS::ECS::Service
    DependsOn:
      - TaskDefinition
    Properties:
      ServiceName: !Ref Name
      Cluster: !Ref Cluster
      Role: !Ref EcsRoleArn
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref LoadBalancerName

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref Name
      TaskRoleArn: !Ref EcsRoleArn
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}
          Essential: true
          Cpu: !Ref Cpu
          Memory: !Ref Memory
          PortMappings:
            - ContainerPort: !Ref ContainerPort
              HostPort: 0
          LogConfiguration:
            LogDriver: awslogs
            Options:
            Options:
                awslogs-group: !Ref AwslogsGroup
                awslogs-region: !Ref AwsRegion
                awslogs-stream-prefix: !Ref AwslogsStreamPrefix
          Environment:
            - Name: Tag
              Value: !Ref Tag
            - Name: RDS_DB_NAME
              Value: !Ref RdsDbName
            - Name: RDS_HOSTNAME
              Value: !Ref RdsHostname
            - Name: RDS_USERNAME
              Value: !Ref RdsUsername
            - Name: RDS_PASSWORD
              Value: !Ref RdsPassword
            - Name: DYNAMODB_ENDPOINT
              Value: !Ref DynamoDbEndpoint
            - Name: SNS_ENDPOINT
              Value: !Ref SnsEndpoint
            - Name: AWS_ACCOUNT_ID
              Value: !Sub ${AWS::AccountId}
            - Name: AWS_REGION
              Value: !Ref AwsRegion
            - Name: AWS_ACCESS_KEY
              Value: !Ref AwsAccessKey
            - Name: AWS_SECRET_KEY
              Value: !Ref AwsSecretKey
            - Name: ENVIRONMENT
              Value: !Ref Environment
            - Name: PORT
              Value: !Ref Port
            - Name: GITHUB_OAUTH_TOKEN
              Value: !Ref GitHubToken
