Parameters:
  Tag:
    Type: String
    Default: latest

  COOKIE_SECRET:
    Type: String

  RDS_DB_NAME:
    Type: String

  RDS_HOSTNAME:
    Type: String

  RDS_PASSWORD:
    Type: String

  RDS_USERNAME:
    Type: String

  DesiredCount:
    Type: Number
    Default: 0

  IAMRole:
    Type: String

  TargetGroup:
    Type: String

  ContainerName:
    Type: String

  ContainerPort:
    Type: String

  ContainerMemory:
    Type: Number

  ContainerCPU:
    Type: Number

  Cluster:
    Type: String

  Repository:
    Type: String

  TaskName:
    Type: String

  TaskCommand:
    Type: String

Resources:
  Service:
    Type: AWS::ECS::Service
    Properties:
      Cluster: !Ref Cluster
      Role: !Ref IAMRole
      DesiredCount: !Ref DesiredCount
      TaskDefinition: !Ref TaskDefinition
      LoadBalancers:
        - ContainerName: !Ref ContainerName
          ContainerPort: !Ref ContainerPort
          TargetGroupArn: !Ref TargetGroup

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskName
      ContainerDefinitions:
        - Name: !Ref Taskname
          Image: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}:${Tag}
          Essential: true
          Memory: !Ref ContainerMemory
          CPU: !Ref ContainerCPU
          PortMappings:
            - ContainerPort: !Ref ContainerPort
            - HostPort: !Ref HostPort
          Environment:
            - Name: Tag
              Value: !Ref Tag
            - Name: COOKIE_SECRET
              Value: !Ref COOKIE_SECRET
            - Name: RDS_DB_NAME
              Value: !Ref RDS_DB_NAME
            - Name: RDS_HOSTNAME
              Value: !Ref RDS_HOSTNAME
            - Name: RDS_PASSWORD
              Value: !Ref RDS_PASSWORD
            - Name: RDS_USERNAME
              Value: !Ref RDS_USERNAME