Parameters:
  GitHubRepo:
    Type: String

  GitHubBranch:
    Type: String

  GitHubToken:
    Type: String

  GitHubUser:
    Type: String

  TemplateBucket:
    Type: String

  Tag:
    Type: String
    Default: latest

  Name:
    Type: String

  ContainerName:
    Type: String

  ContainerPort:
    Type: Number
    Default: 3000

  Port:
    Type: Number
    Default: 3000

  DesiredCount:
    Type: Number
    Default: 0

  LoadBalancerName:
    Type: String

  Cluster:
    Type: String

  Repository:
    Type: String

  RdsDbName:
    Type: String

  RdsHostname:
    Type: String

  RdsUsername:
    Type: String

  RdsPassword:
    Type: String

  AwslogsGroup:
    Type: String

  AwslogsStreamPrefix:
    Type: String

  DynamoDbEndpoint:
    Type: String
    Default: dynamodb.us-east-1.amazonaws.com

  SnsEndpoint:
    Type: String
    Default: sns.us-east-1.amazonaws.com

  AwsRegion:
    Type: String

  AwsAccessKey:
    Type: String

  AwsSecretKey:
    Type: String

  Environment:
    Type: String

  SlackNotifierLambdaKey:
    Description: The Lambda function that does Slack notifications
    Type: String
    Default: slack-notifier.zip

  SlackWebHook:
    Description: The Webhook created that notification will be sent to.
    Type: String

Resources:

  CloudFormationExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "cloudformation.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - elasticloadbalancing:*
                  - codebuild:*
                  - codepipeline:*
                  - ecs:*
                  - ecr:*
                  - iam:*
                  - lambda:*

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "codebuild.amazonaws.com", "ec2.amazonaws.com", "ecs.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ecr:GetAuthorizationToken
                  - codebuild:*
              - Resource: !Sub arn:aws:s3:::${ArtifactBucket}/*
                Effect: Allow
                Action:
                  - s3:*
              - Resource: !Sub arn:aws:ecr:${AWS::Region}:${AWS::AccountId}:repository/${Repository}
                Effect: Allow
                Action:
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ecr:BatchCheckLayerAvailability
                  - ecr:PutImage
                  - ecr:InitiateLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:CompleteLayerUpload

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument: |
        {
            "Statement": [{
                "Effect": "Allow",
                "Principal": { "Service": [ "codepipeline.amazonaws.com" ]},
                "Action": [ "sts:AssumeRole" ]
            }]
        }
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource:
                  - !Sub arn:aws:s3:::${ArtifactBucket}/*
                  - !Sub arn:aws:s3:::${TemplateBucket}
                  - !Sub arn:aws:s3:::${TemplateBucket}/*
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketVersioning
              - Resource: "*"
                Effect: Allow
                Action:
                  - codebuild:*
                  - cloudformation:*
                  - codepipeline:*
                  - lambda:*
                  - ecr:*
                  - ecs:*
                  - iam:PassRole

  ArtifactBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${Name}-codepipeline-artifacts
    DeletionPolicy: Retain

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Name}-codebuild-build
      Artifacts:
        Location: !Ref ArtifactBucket
        Type: "S3"
      Source:
        Location: !Sub https://github.com/FoundryAI/${GitHubRepo}.git
        Type: "GITHUB"
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - $(aws ecr get-login)
                - TAG="$([ $(echo $CODEBUILD_INITIATOR | cut -c 1-12) = codepipeline ] && echo $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8) || echo $(echo $CODEBUILD_SOURCE_VERSION | sed "s/\//\-/g"))"
            build:
              commands:
                - docker build --tag "${REPOSITORY_URI}:${TAG}" .
            post_build:
              commands:
                - docker push "${REPOSITORY_URI}:${TAG}"
                - printf '{"tag":"%s"}' $TAG > build.json
          artifacts:
            files: build.json
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/docker:1.12.1"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}
      ServiceRole: !Ref CodeBuildServiceRole

  CodeBuildProjectTest:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${Name}-codebuild-test
      Artifacts:
        Location: !Ref ArtifactBucket
        Type: "S3"
      Source:
        Location: !Sub https://github.com/FoundryAI/${GitHubRepo}.git
        Type: "GITHUB"
        BuildSpec: |
          version: 0.2
          phases:
            pre_build:
              commands:
                - curl -L "https://github.com/docker/compose/releases/download/1.15.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && chmod +x /usr/local/bin/docker-compose
                - TAG="$([ $(echo $CODEBUILD_INITIATOR | cut -c 1-12) = codepipeline ] && echo $(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8) || echo $(echo $CODEBUILD_SOURCE_VERSION | sed "s/\//\-/g"))"
                - docker network create hud_ai_local
            build:
              commands:
                - touch .env
                - docker-compose -f docker-compose.yml -f docker-compose.test.yml run api
            post_build:
              commands:
                - printf '{"tag":"%s"}' $TAG > build.json
          artifacts:
            files: build.json
      Environment:
        ComputeType: "BUILD_GENERAL1_SMALL"
        Image: "aws/codebuild/docker:1.12.1"
        Type: "LINUX_CONTAINER"
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: REPOSITORY_URI
            Value: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${Repository}
      ServiceRole: !Ref CodeBuildServiceRole


  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: !Sub ${Name}-codepipeline
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref ArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: App
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubUser
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubToken
              OutputArtifacts:
                - Name: App
              RunOrder: 1
            - Name: Template
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              OutputArtifacts:
                - Name: Template
              RunOrder: 1
              Configuration:
                S3Bucket: !Ref TemplateBucket
                S3ObjectKey: templates.zip
        - Name: BuildTest
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProject
              InputArtifacts:
                - Name: App
              OutputArtifacts:
                - Name: BuildOutput
              RunOrder: 1
            - Name: Test
              ActionTypeId:
                Category: Test
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              Configuration:
                ProjectName: !Ref CodeBuildProjectTest
              InputArtifacts:
                - Name: App
              OutputArtifacts:
                - Name: TestOutput
              RunOrder: 1
            - Name: PassedSuccessfuly
              InputArtifacts: []
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: '1'
                Provider: Lambda
              OutputArtifacts: []
              RunOrder: 2
              Configuration:
                FunctionName: !Ref SlackNotifier
                UserParameters: !Sub |
                  {
                    "webhooks": "https://hooks.slack.com/services/${SlackWebHook}",
                    "message": "${Name} build & test passed successfully"
                  }
        - Name: Deploy
          Actions:
            - Name: CreateChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: CloudFormation
              Configuration:
                ChangeSetName: !Sub ${Name}-change-set
                ActionMode: CHANGE_SET_REPLACE
                StackName: !Sub ${Name}-deployment-stack
                Capabilities: CAPABILITY_NAMED_IAM
                TemplatePath: Template::ecs-service.yaml
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                ParameterOverrides: !Sub |
                  {
                    "AwsAccessKey": "${AwsAccessKey}",
                    "AwslogsGroup": "${AwslogsGroup}",
                    "AwslogsStreamPrefix": "${AwslogsStreamPrefix}",
                    "AwsRegion": "${AwsRegion}",
                    "AwsSecretKey": "${AwsSecretKey}",
                    "Cluster": "${Cluster}",
                    "ContainerName": "${ContainerName}",
                    "ContainerPort": "${ContainerPort}",
                    "Environment": "${Environment}",
                    "DesiredCount": "${DesiredCount}",
                    "LoadBalancerName": "${LoadBalancerName}",
                    "Name": "${Name}",
                    "RdsDbName": "${RdsDbName}",
                    "RdsHostname": "${RdsHostname}",
                    "RdsUsername": "${RdsUsername}",
                    "RdsPassword": "${RdsPassword}",
                    "Repository": "${Repository}",
                    "Tag" : { "Fn::GetParam" : [ "BuildOutput", "build.json", "tag" ] },
                    "GitHubToken": "${GitHubToken}"
                  }
              InputArtifacts:
                - Name: Template
                - Name: BuildOutput
              RunOrder: 1
            - Name: ExecuteChangeSet
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CHANGE_SET_EXECUTE
                ChangeSetName: !Sub ${Name}-change-set
                RoleArn: !GetAtt CloudFormationExecutionRole.Arn
                StackName: !Sub ${Name}-deployment-stack
              RunOrder: 2


  SlackNotifier:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
    Properties:
      Handler: main.send_post
      Role: !GetAtt LambdaRole.Arn
      Timeout: 5
      Runtime: python2.7
      MemorySize: 128
      Code:
        S3Bucket: !Ref TemplateBucket
        S3Key: slack-notifier.zip

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: [lambda.amazonaws.com]
            Action: ['sts:AssumeRole']
      Path: /

  LambdaRolePolicies:
    Type: AWS::IAM::Policy
    DependsOn: LambdaRole
    Properties:
      PolicyName: LambdaPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action: lambda:InvokeFunction
            Resource: !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:*
          - Effect: Allow
            Action: ['ec2:Describe*']
            Resource: "*"
          - Effect: Allow
            Action: 'logs:*'
            Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
          - Effect: Allow
            Action: 'sns:*'
            Resource: ["*"]
          - Effect: Allow
            Action: 'codepipeline:*'
            Resource: ["*"]
      Roles: [ !Ref LambdaRole ]

Outputs:
  PipelineUrl:
    Value: !Sub https://console.aws.amazon.com/codepipeline/home?region=${AWS::Region}#/view/${Pipeline}
